### ISSUE TITLE
`removeTrackingURL.plugin.js` does not belong to any branch

### ISSUE THREAD

**Issue by Obegg** [wotanut/DiscordStuff#15]
original - 1.0.6
https://github.com/wotanut/DiscordStuff/blob/main/plugins/dist/removeTrackingURL.plugin.js

updated - 1.0.7 - (weird link and does not belong to any branch)
https://github.com/wotanut/DiscordStuff/blob/e39a132471b2d894b35785be4e2fe206f596d421/plugins/dist/removeTrackingURL.plugin.js

please update it on the original branch

**Comment by wotanut** [comment]
I think it's fixed, I forgot to merge some code onto main. Bit confused how you got this error though.

**Comment by Obegg** [comment]
on discord it showed that there's an outdated plugin

**Comment by wotanut** [comment]
Did the plugin fail to update?

**Comment by Obegg** [comment]
Uhm, I did not test it if it updates or not

**Comment by wotanut** [comment]
Ok, can you let me know if it updates please

**Comment by Obegg** [comment]
it updates, thank you, closing this issue
