### ISSUE TITLE
Add the DDLInstagram feature to removeTrackingURL (an alternative Instagram that converts to embed text and images or videos).

### ISSUE THREAD

**Issue by ryukora** [wotanut/DiscordStuff#5]
Can you add `ddinstagram.com` (replacing Instagram alternative links for conversion and embedding with text and video) to [removeTrackingURL](https://github.com/wotanut/DiscordStuff/blob/main/plugins/dist/removeTrackingURL.plugin.js)? I'd like to if you can do it.

These are examples of IG reels and posts:

`www.instagram.com/reel/[videolink]/?igshid=[trackinglink]A==]`
`www.instagram.com/p/[postsimagelink]/?utm_source=ig_web_copy_link&igshid=[trackinglink]==`

You can remove those tracking links if you don't need them.

Thanks! 🙏

**Comment by wotanut** [comment]
Hi there, sorry for the slow response.

This is definitely something I can do and I’ll put it in my list of things to do.

**Comment by nxzlem** [comment]
> Hi there, sorry for the slow response.
> 
> This is definitely something I can do and I’ll put it in my list of things to do.

Okay, good luck with the project! I hope you can do it as well as you can.

**Comment by ryukora** [comment]
> Hi there, sorry for the slow response.
> 
> This is definitely something I can do and I’ll put it in my list of things to do.

Maybe the REGEX of Instagram reels and posts should work like this.

```js


    const REGEX = {
		"instagram_reels": /((?:https|http)\:\/\/(?:www\.)?instagram\.com\/(?:reel|reels)\/[a-zA-Z0-9-_]+\/?(?:\?\S+)?)\S*/g,
		"instagram_posts": /((?:https|http)\:\/\/(?:www\.)?instagram\.com\/p\/[a-zA-Z0-9-_]+\/?(?:\?\S+)?)\S*/g,



```

You can consider fixing what I just made, or you can make it yourself.
Thanks!

**Comment by wotanut** [comment]
Since this pr was opened (and since the project started) there are now two plugins that I think can do this better than this one:

- [SocialMediaLinkConverter](https://betterdiscord.app/plugin/SocialMediaLinkConverter)
- [TextReplacer](https://betterdiscord.app/plugin/TextReplacer)

I think that this should be included there instead of on this plugin as it's more relevant to them. Apologies for the wait as well.
